# Generated by Django 2.2.3 on 2019-07-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='costs',
            field=models.FloatField(default=0, verbose_name='total cost'),
        ),
    ]
