# Generated by Django 2.2.7 on 2021-01-16 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_category_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='desciption',
            new_name='description',
        ),
    ]
