# Generated by Django 3.1.5 on 2021-02-17 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_auto_20210117_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'ordering': ['-timestamp']},
        ),
    ]
