# Generated by Django 3.1.5 on 2021-02-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_auto_20210217_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='costs',
            field=models.IntegerField(default=0, verbose_name='total cost'),
        ),
    ]
