# Generated by Django 2.2.7 on 2021-01-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='rupees',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='title',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='description',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
