# Generated by Django 2.2.7 on 2021-01-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_auto_20210117_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
