# Generated by Django 3.1.5 on 2021-02-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_auto_20210117_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-timestamp']},
        ),
    ]
