# Generated by Django 3.1.5 on 2021-02-17 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0006_auto_20210217_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={},
        ),
    ]
